name: tweet

# Controls when the action will run. 
on:
  schedule:
  - cron: "0 19 * * *" # UTC time (-1 en hiver et -2 en été)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Données Présidentielles
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      run: |
        python src/elections_presidentielles_moyenne_mobile_intentions.py
        python src/graphique.py
        python src/tweet_chiffres_quotidiens.py
    - uses: stefanzweifel/git-auto-commit-action@v4
    
